## Student Attendance Analytics with Pandas

In [ ]:
import pandas as pd
import numpy as np

#### Section 0: Data Loading

In [3]:
import pandas as pd
df = pd.read_excel("aiml_attendance.xlsx")
df

,Roll No,Student Name,Subject,Total Classes,Present,Absent,Excused,Attendance %,Status,Classes Needed (75%),Last Present Date,Consecutive Absences
0,4MW24AI001,ABHIJITH,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67%,Critical,4 more,2026-10-09,1
1,4MW24AI002,ABHISHEK KRISHNA P,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67%,Critical,4 more,2026-10-09,1
2,4MW24AI003,ADITYA,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8%,Critical,32 more,2026-09-22,5
3,4MW24AI004,AKSHATA JAKAREDDY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
4,4MW24AI005,ANANYA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
5,4MW24AI006,ANANYASHREE,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
6,4MW24AI007,ANKITA TARANATH MESTA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
7,4MW24AI008,ANVITH S SHERIGAR,Data Science & GenAI - 3nd Yr- AIML,12,12,0,0,100%,Safe,✓ Met,2026-10-10,0
8,4MW24AI009,APEKSHA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
9,4MW24AI010,ARLENE VELORA FERNANDES,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-09,1
10,4MW24AI011,ASHRITHA,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-09,1
11,4MW24AI013,AYESHA REEMAN,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-06,2
12,4MW24AI014,DHANRAJ L POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,6,6,0,50%,Critical,12 more,2026-10-06,2
13,4MW24AI015,DHANYATHA R,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-09,1
14,4MW24AI016,G BHUPATHE,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
15,4MW24AI018,HARSHAL G POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-09,1
16,4MW24AI019,JNANESH . S,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-09,1
17,4MW24AI020,KEERTHAN KRISHNA SHERIGAR,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-09,1
18,4MW24AI021,KISHAN J,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25%,Critical,24 more,2026-09-29,3
19,4MW24AI022,KUNDAR KASHISH CHANDRA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-10,0
20,4MW24AI023,LAKSHITHA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-10,0
21,4MW24AI024,MANEESH SHETTY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
22,4MW24AI025,MANMITHA,Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17%,Critical,28 more,2026-10-06,2
23,4MW24AI026,MAYUR,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-06,2
24,4MW24AI027,MOHAMMED SIMAK,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-06,2
25,4MW24AI028,MOURYA RAJ H N,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25%,Critical,24 more,2026-09-22,5
26,4MW24AI029,MUHAMMED NASHIT,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
27,4MW24AI030,NAVYA,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25%,Critical,24 more,2026-10-06,2
28,4MW24AI031,PAVITHRA NAYAK,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
29,4MW24AI032,PRAGNYA R,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
30,4MW24AI033,PRAMOD ACHAR,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25%,Critical,24 more,2026-10-06,2
31,4MW24AI034,RAJATH H S,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25%,Critical,24 more,2026-10-06,2
32,4MW24AI035,RAJATH K K,Data Science & GenAI - 3nd Yr- AIML,12,0,12,0,0%,Critical,36 more,Never,12
33,4MW24AI036,RAJU ASHOKA RATHOD,Data Science & GenAI - 3nd Yr- AIML,12,0,12,0,0%,Critical,36 more,Never,12
34,4MW24AI037,RAKESH HEGDE,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
35,4MW24AI038,RASHMI,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8%,Critical,32 more,2026-10-06,2
36,4MW24AI039,RITHIN,Data Science & GenAI - 3nd Yr- AIML,12,4,8,0,33%,Critical,20 more,2026-10-06,2
37,4MW24AI041,SANIKA,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25%,Critical,24 more,2026-10-06,2
38,4MW24AI042,SHAMANTH K,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-09,1
39,4MW24AI043,SHETTY RASHIK RATHNAKAR,Data Science & GenAI - 3nd Yr- AIML,12,5,7,0,42%,Critical,16 more,2026-10-06,2
40,4MW24AI044,SHODAN B POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-10,0
41,4MW24AI045,SHRAVYA,Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17%,Critical,28 more,2026-09-08,9
42,4MW24AI046,SHREESH A DEVADIGA,Data Science & GenAI - 3nd Yr- AIML,12,12,0,0,100%,Safe,✓ Met,2026-10-10,0
43,4MW24AI047,SHRIYA DEVADIGA,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
44,4MW24AI048,SINCHANA (SUNDARA MADIVALA),Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17%,Critical,28 more,2026-10-06,2
45,4MW24AI049,SINCHANA (MURALI KUPPAYYA MOGAVEERA),Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
46,4MW24AI050,SPOORTHI,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
47,4MW24AI052,SUPRAJA S M,Data Science & GenAI - 3nd Yr- AIML,12,6,6,0,50%,Critical,12 more,2026-10-09,1
48,4MW24AI053,SUPRITHA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
49,4MW24AI054,TEJAS,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-06,2
50,4MW24AI055,TRIPTHI H PADMASHALI,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-09,1
51,4MW24AI056,VAMSH,Data Science & GenAI - 3nd Yr- AIML,12,4,8,0,33%,Critical,20 more,2026-10-06,2
52,4MW24AI057,VANDANA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
53,4MW24AI058,VIGNESH ADIGA,Data Science & GenAI - 3nd Yr- AIML,12,7,5,0,58%,Critical,8 more,2026-09-25,4
54,4MW24AI059,VIHAAN S,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67%,Critical,4 more,2026-10-10,0
55,4MW24AI060,YASHASVI K POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
56,4MW24AI061,Raksha,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
57,4MW25AI400,Dhananjay,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-06,2
58,4MW25AI401,Omkar Rane,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8%,Critical,32 more,2026-09-08,9

#### Section 1: Data Inspection

In [4]:
"""Q1. Display the first 10 rows, the shape of the DataFrame, and the data types of each column."""
#-----------------------------Write Solution Code-----------------------------
import pandas as pd

print(df.head(10))
print(df.shape)
print(df.dtypes)

      Roll No             Student Name                               Subject  \
0  4MW24AI001                 ABHIJITH  Data Science & GenAI - 3nd Yr- AIML
1  4MW24AI002       ABHISHEK KRISHNA P  Data Science & GenAI - 3nd Yr- AIML
2  4MW24AI003                   ADITYA  Data Science & GenAI - 3nd Yr- AIML
3  4MW24AI004        AKSHATA JAKAREDDY  Data Science & GenAI - 3nd Yr- AIML
4  4MW24AI005                   ANANYA  Data Science & GenAI - 3nd Yr- AIML
5  4MW24AI006              ANANYASHREE  Data Science & GenAI - 3nd Yr- AIML
6  4MW24AI007    ANKITA TARANATH MESTA  Data Science & GenAI - 3nd Yr- AIML
7  4MW24AI008        ANVITH S SHERIGAR  Data Science & GenAI - 3nd Yr- AIML
8  4MW24AI009                  APEKSHA  Data Science & GenAI - 3nd Yr- AIML
9  4MW24AI010  ARLENE VELORA FERNANDES  Data Science & GenAI - 3nd Yr- AIML

   Total Classes  Present  Absent  Excused Attendance %    Status  \
0             12        8       4        0          67%  Critical
1             12        8       4        0          67%  Critical
2             12        1      11        0           8%  Critical
3             12       11       1        0          92%      Safe
4             12       10       2        0          83%   Warning
5             12       10       2        0          83%   Warning
6             12       10       2        0          83%   Warning
7             12       12       0        0         100%      Safe
8             12       10       2        0          83%   Warning
9             12        9       3        0          75%   Warning

  Classes Needed (75%) Last Present Date  Consecutive Absences
0               4 more        2026-10-09                     1
1               4 more        2026-10-09                     1
2              32 more        2026-09-22                     5
3                ✓ Met        2026-10-10                     0
4                ✓ Met        2026-10-09                     1
5                ✓ Met        2026-10-09                     1
6                ✓ Met        2026-10-09                     1
7                ✓ Met        2026-10-10                     0
8                ✓ Met        2026-10-09                     1
9                ✓ Met        2026-10-09                     1
(59, 12)
Roll No                 object
Student Name            object
Subject                 object
Total Classes            int64
Present                  int64
Absent                   int64
Excused                  int64
Attendance %            object
Status                  object
Classes Needed (75%)    object
Last Present Date       object
Consecutive Absences     int64
dtype: object

In [5]:
"""Q2. Check for missing values in each column. Identify which columns have null values (especially Last Present Date with "Never") and report the count. """
#-----------------------------Write Solution Code-----------------------------
print(df.isnull().sum())
print((df == "Never").sum())
print(df['Last Present Date'].value_counts(dropna=False))

Roll No                 0
Student Name            0
Subject                 0
Total Classes           0
Present                 0
Absent                  0
Excused                 0
Attendance %            0
Status                  0
Classes Needed (75%)    0
Last Present Date       0
Consecutive Absences    0
dtype: int64
Roll No                 0
Student Name            0
Subject                 0
Total Classes           0
Present                 0
Absent                  0
Excused                 0
Attendance %            0
Status                  0
Classes Needed (75%)    0
Last Present Date       2
Consecutive Absences    0
dtype: int64
Last Present Date
2026-10-09    22
2026-10-06    16
2026-10-10    13
2026-09-22     2
Never          2
2026-09-08     2
2026-09-29     1
2026-09-25     1
Name: count, dtype: int64

In [6]:
"""Q3. Rename the columns to snake_case (e.g., Roll No → roll_no, Student Name → student_name, Attendance % → attendance_pct). Display the updated column list."""
#-----------------------------Write Solution Code-----------------------------
df.columns = df.columns.str.strip().str.lower().str.replace('%','pct').str.replace(r'[^\w]+','_', regex=True).str.strip('_')
print(df.columns.tolist())

['roll_no', 'student_name', 'subject', 'total_classes', 'present', 'absent', 'excused', 'attendance_pct', 'status', 'classes_needed_75pct', 'last_present_date', 'consecutive_absences']

In [11]:
"""Q4. Convert Attendance % from string format (e.g., "64%") to a numeric float column (0.64 or 64.0). Also convert Last Present Date to datetime, handling "Never" as NaT."""
#-----------------------------Write Solution Code-----------------------------
df['attendance_pct'] = df['attendance_pct'].astype(str).str.replace('%','', regex=False).str.strip()
df['attendance_pct'] = pd.to_numeric(df['attendance_pct'], errors='coerce')

df['last_present_date'] = df['last_present_date'].replace('Never', pd.NaT)
df['last_present_date'] = pd.to_datetime(df['last_present_date'], errors='coerce')

print(df[['attendance_pct', 'last_present_date']].head(10))

   attendance_pct last_present_date
0            67.0        2026-10-09
1            67.0        2026-10-09
2             8.0        2026-09-22
3            92.0        2026-10-10
4            83.0        2026-10-09
5            83.0        2026-10-09
6            83.0        2026-10-09
7           100.0        2026-10-10
8            83.0        2026-10-09
9            75.0        2026-10-09

#### Section 2: Filtering & Selection

In [12]:
"""Q5. Filter and display all students whose Status is "Critical". Sort them by Attendance % in ascending order."""
#-----------------------------Write Solution Code-----------------------------
critical_df = df[df['status'] == 'Critical'].sort_values('attendance_pct')
print(critical_df)

       roll_no                 student_name  \
32  4MW24AI035                   RAJATH K K
33  4MW24AI036           RAJU ASHOKA RATHOD
2   4MW24AI003                       ADITYA
35  4MW24AI038                       RASHMI
58  4MW25AI401                   Omkar Rane
22  4MW24AI025                     MANMITHA
41  4MW24AI045                      SHRAVYA
44  4MW24AI048  SINCHANA (SUNDARA MADIVALA)
30  4MW24AI033                 PRAMOD ACHAR
37  4MW24AI041                       SANIKA
31  4MW24AI034                   RAJATH H S
25  4MW24AI028               MOURYA RAJ H N
18  4MW24AI021                     KISHAN J
27  4MW24AI030                        NAVYA
51  4MW24AI056                        VAMSH
36  4MW24AI039                       RITHIN
39  4MW24AI043      SHETTY RASHIK RATHNAKAR
47  4MW24AI052                  SUPRAJA S M
12  4MW24AI014            DHANRAJ L POOJARY
53  4MW24AI058                VIGNESH ADIGA
0   4MW24AI001                     ABHIJITH
1   4MW24AI002           ABHISHEK KRISHNA P
54  4MW24AI059                     VIHAAN S

                                 subject  total_classes  present  absent  \
32  Data Science & GenAI - 3nd Yr- AIML              12        0      12
33  Data Science & GenAI - 3nd Yr- AIML              12        0      12
2   Data Science & GenAI - 3nd Yr- AIML              12        1      11
35  Data Science & GenAI - 3nd Yr- AIML              12        1      11
58  Data Science & GenAI - 3nd Yr- AIML              12        1      11
22  Data Science & GenAI - 3nd Yr- AIML              12        2      10
41  Data Science & GenAI - 3nd Yr- AIML              12        2      10
44  Data Science & GenAI - 3nd Yr- AIML              12        2      10
30  Data Science & GenAI - 3nd Yr- AIML              12        3       9
37  Data Science & GenAI - 3nd Yr- AIML              12        3       9
31  Data Science & GenAI - 3nd Yr- AIML              12        3       9
25  Data Science & GenAI - 3nd Yr- AIML              12        3       9
18  Data Science & GenAI - 3nd Yr- AIML              12        3       9
27  Data Science & GenAI - 3nd Yr- AIML              12        3       9
51  Data Science & GenAI - 3nd Yr- AIML              12        4       8
36  Data Science & GenAI - 3nd Yr- AIML              12        4       8
39  Data Science & GenAI - 3nd Yr- AIML              12        5       7
47  Data Science & GenAI - 3nd Yr- AIML              12        6       6
12  Data Science & GenAI - 3nd Yr- AIML              12        6       6
53  Data Science & GenAI - 3nd Yr- AIML              12        7       5
0   Data Science & GenAI - 3nd Yr- AIML              12        8       4
1   Data Science & GenAI - 3nd Yr- AIML              12        8       4
54  Data Science & GenAI - 3nd Yr- AIML              12        8       4

    excused  attendance_pct    status classes_needed_75pct last_present_date  \
32        0             0.0  Critical              36 more               NaT
33        0             0.0  Critical              36 more               NaT
2         0             8.0  Critical              32 more        2026-09-22
35        0             8.0  Critical              32 more        2026-10-06
58        0             8.0  Critical              32 more        2026-09-08
22        0            17.0  Critical              28 more        2026-10-06
41        0            17.0  Critical              28 more        2026-09-08
44        0            17.0  Critical              28 more        2026-10-06
30        0            25.0  Critical              24 more        2026-10-06
37        0            25.0  Critical              24 more        2026-10-06
31        0            25.0  Critical              24 more        2026-10-06
25        0            25.0  Critical              24 more        2026-09-22
18        0            25.0  Critical              24 more        2026-09-29
27        0            25.0  Critical              24 more        2026-10-06
51        0            33.0  Critical              20 more        2026-10-06
36        0            33.0  Critical              20 more        2026-10-06
39        0            42.0  Critical              16 more        2026-10-06
47        0            50.0  Critical              12 more        2026-10-09
12        0            50.0  Critical              12 more        2026-10-06
53        0            58.0  Critical               8 more        2026-09-25
0         0            67.0  Critical               4 more        2026-10-09
1         0            67.0  Critical               4 more        2026-10-09
54        0            67.0  Critical               4 more        2026-10-10

    consecutive_absences
32                    12
33                    12
2                      5
35                     2
58                     9
22                     2
41                     9
44                     2
30                     2
37                     2
31                     2
25                     5
18                     3
27                     2
51                     2
36                     2
39                     2
47                     1
12                     2
53                     4
0                      1
1                      1
54                     0

In [13]:
"""Q6. Extract all students who have 0 present days (fully absent). List their roll numbers, names, and consecutive absences."""
#-----------------------------Write Solution Code-----------------------------
absent_df = df[df['present'] == 0][['roll_no','student_name','consecutive_absences']]
print(absent_df)

       roll_no        student_name  consecutive_absences
32  4MW24AI035          RAJATH K K                    12
33  4MW24AI036  RAJU ASHOKA RATHOD                    12

In [14]:
"""Q7. Using .loc and .iloc, display:
(a) All "Safe" students using .loc
(b) The first 15 rows and columns 2-6 using .iloc """
#-----------------------------Write Solution Code-----------------------------
print(df.loc[df['status'] == 'Safe'])
print(df.iloc[0:15, 2:6])

       roll_no                          student_name  \
3   4MW24AI004                     AKSHATA JAKAREDDY
7   4MW24AI008                     ANVITH S SHERIGAR
14  4MW24AI016                            G BHUPATHE
15  4MW24AI018                     HARSHAL G POOJARY
16  4MW24AI019                           JNANESH . S
17  4MW24AI020             KEERTHAN KRISHNA SHERIGAR
21  4MW24AI024                        MANEESH SHETTY
26  4MW24AI029                       MUHAMMED NASHIT
29  4MW24AI032                             PRAGNYA R
38  4MW24AI042                            SHAMANTH K
42  4MW24AI046                    SHREESH A DEVADIGA
43  4MW24AI047                       SHRIYA DEVADIGA
45  4MW24AI049  SINCHANA (MURALI KUPPAYYA MOGAVEERA)

                                 subject  total_classes  present  absent  \
3   Data Science & GenAI - 3nd Yr- AIML              12       11       1
7   Data Science & GenAI - 3nd Yr- AIML              12       12       0
14  Data Science & GenAI - 3nd Yr- AIML              12       11       1
15  Data Science & GenAI - 3nd Yr- AIML              12       11       1
16  Data Science & GenAI - 3nd Yr- AIML              12       11       1
17  Data Science & GenAI - 3nd Yr- AIML              12       11       1
21  Data Science & GenAI - 3nd Yr- AIML              12       11       1
26  Data Science & GenAI - 3nd Yr- AIML              12       11       1
29  Data Science & GenAI - 3nd Yr- AIML              12       11       1
38  Data Science & GenAI - 3nd Yr- AIML              12       11       1
42  Data Science & GenAI - 3nd Yr- AIML              12       12       0
43  Data Science & GenAI - 3nd Yr- AIML              12       11       1
45  Data Science & GenAI - 3nd Yr- AIML              12       11       1

    excused  attendance_pct status classes_needed_75pct last_present_date  \
3         0            92.0   Safe                ✓ Met        2026-10-10
7         0           100.0   Safe                ✓ Met        2026-10-10
14        0            92.0   Safe                ✓ Met        2026-10-10
15        0            92.0   Safe                ✓ Met        2026-10-09
16        0            92.0   Safe                ✓ Met        2026-10-09
17        0            92.0   Safe                ✓ Met        2026-10-09
21        0            92.0   Safe                ✓ Met        2026-10-10
26        0            92.0   Safe                ✓ Met        2026-10-10
29        0            92.0   Safe                ✓ Met        2026-10-10
38        0            92.0   Safe                ✓ Met        2026-10-09
42        0           100.0   Safe                ✓ Met        2026-10-10
43        0            92.0   Safe                ✓ Met        2026-10-10
45        0            92.0   Safe                ✓ Met        2026-10-10

    consecutive_absences
3                      0
7                      0
14                     0
15                     1
16                     1
17                     1
21                     0
26                     0
29                     0
38                     1
42                     0
43                     0
45                     0
                                 subject  total_classes  present  absent
0   Data Science & GenAI - 3nd Yr- AIML              12        8       4
1   Data Science & GenAI - 3nd Yr- AIML              12        8       4
2   Data Science & GenAI - 3nd Yr- AIML              12        1      11
3   Data Science & GenAI - 3nd Yr- AIML              12       11       1
4   Data Science & GenAI - 3nd Yr- AIML              12       10       2
5   Data Science & GenAI - 3nd Yr- AIML              12       10       2
6   Data Science & GenAI - 3nd Yr- AIML              12       10       2
7   Data Science & GenAI - 3nd Yr- AIML              12       12       0
8   Data Science & GenAI - 3nd Yr- AIML              12       10       2
9   Data Science & GenAI - 3nd Yr- AIML              12        9       3
10  Data Science & GenAI - 3nd Yr- AIML              12        9       3
11  Data Science & GenAI - 3nd Yr- AIML              12        9       3
12  Data Science & GenAI - 3nd Yr- AIML              12        6       6
13  Data Science & GenAI - 3nd Yr- AIML              12        9       3
14  Data Science & GenAI - 3nd Yr- AIML              12       11       1

In [15]:
"""Q8. Find all students whose Consecutive Absences is greater than or equal to 5. Display their name, status, and last present date."""
#-----------------------------Write Solution Code-----------------------------
print(df[df['consecutive_absences'] >= 5][['student_name','status','last_present_date']])

          student_name    status last_present_date
2               ADITYA  Critical        2026-09-22
25      MOURYA RAJ H N  Critical        2026-09-22
32          RAJATH K K  Critical               NaT
33  RAJU ASHOKA RATHOD  Critical               NaT
41             SHRAVYA  Critical        2026-09-08
58          Omkar Rane  Critical        2026-09-08

### Section 3: Grouping & Aggregation

In [16]:
"""Q9. Group the data by Status and compute: 
a) Count of students 
b) Average attendance %  
c) Maximum consecutive absences"""
#-----------------------------Write Solution Code-----------------------------
print(df.groupby('status').agg(
    student_count=('roll_no','count'),
    avg_attendance=('attendance_pct','mean'),
    max_consecutive_absences=('consecutive_absences','max')
))

          student_count  avg_attendance  max_consecutive_absences
status
Critical             23       30.086957                        12
Safe                 13       93.230769                         1
Warning              23       80.565217                         2

In [19]:
"""Q10. Create a new column Attendance Category:
≥ 90% → "Excellent"
75-89% → "Good"
60-74% → "Average"
< 60% → "Poor"
Then use groupby() to count students in each category."""
#-----------------------------Write Solution Code-----------------------------
def get_category(x):
    if x >= 90:
        return "Excellent"
    elif x >= 75:
        return "Good"
    elif x >= 60:
        return "Average"
    else:
        return "Poor"
    df['attendance_category'] = df['attendance_pct'].apply(get_category)
    print(df.groupby('attendance_category').size())

## Student Attendance Analytics with Pandas

In [ ]:
import pandas as pd
import numpy as np

#### Section 0: Data Loading

In [ ]:
import pandas as pd
df = pd.read_excel("aiml_attendance.xlsx")
df

,Roll No,Student Name,Subject,Total Classes,Present,Absent,Excused,Attendance %,Status,Classes Needed (75%),Last Present Date,Consecutive Absences
0,4MW24AI001,ABHIJITH,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67%,Critical,4 more,2026-10-09,1
1,4MW24AI002,ABHISHEK KRISHNA P,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67%,Critical,4 more,2026-10-09,1
2,4MW24AI003,ADITYA,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8%,Critical,32 more,2026-09-22,5
3,4MW24AI004,AKSHATA JAKAREDDY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
4,4MW24AI005,ANANYA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
5,4MW24AI006,ANANYASHREE,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
6,4MW24AI007,ANKITA TARANATH MESTA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
7,4MW24AI008,ANVITH S SHERIGAR,Data Science & GenAI - 3nd Yr- AIML,12,12,0,0,100%,Safe,✓ Met,2026-10-10,0
8,4MW24AI009,APEKSHA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
9,4MW24AI010,ARLENE VELORA FERNANDES,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-09,1
10,4MW24AI011,ASHRITHA,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-09,1
11,4MW24AI013,AYESHA REEMAN,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-06,2
12,4MW24AI014,DHANRAJ L POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,6,6,0,50%,Critical,12 more,2026-10-06,2
13,4MW24AI015,DHANYATHA R,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-09,1
14,4MW24AI016,G BHUPATHE,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
15,4MW24AI018,HARSHAL G POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-09,1
16,4MW24AI019,JNANESH . S,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-09,1
17,4MW24AI020,KEERTHAN KRISHNA SHERIGAR,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-09,1
18,4MW24AI021,KISHAN J,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25%,Critical,24 more,2026-09-29,3
19,4MW24AI022,KUNDAR KASHISH CHANDRA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-10,0
20,4MW24AI023,LAKSHITHA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-10,0
21,4MW24AI024,MANEESH SHETTY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
22,4MW24AI025,MANMITHA,Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17%,Critical,28 more,2026-10-06,2
23,4MW24AI026,MAYUR,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-06,2
24,4MW24AI027,MOHAMMED SIMAK,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-06,2
25,4MW24AI028,MOURYA RAJ H N,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25%,Critical,24 more,2026-09-22,5
26,4MW24AI029,MUHAMMED NASHIT,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
27,4MW24AI030,NAVYA,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25%,Critical,24 more,2026-10-06,2
28,4MW24AI031,PAVITHRA NAYAK,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
29,4MW24AI032,PRAGNYA R,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
30,4MW24AI033,PRAMOD ACHAR,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25%,Critical,24 more,2026-10-06,2
31,4MW24AI034,RAJATH H S,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25%,Critical,24 more,2026-10-06,2
32,4MW24AI035,RAJATH K K,Data Science & GenAI - 3nd Yr- AIML,12,0,12,0,0%,Critical,36 more,Never,12
33,4MW24AI036,RAJU ASHOKA RATHOD,Data Science & GenAI - 3nd Yr- AIML,12,0,12,0,0%,Critical,36 more,Never,12
34,4MW24AI037,RAKESH HEGDE,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
35,4MW24AI038,RASHMI,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8%,Critical,32 more,2026-10-06,2
36,4MW24AI039,RITHIN,Data Science & GenAI - 3nd Yr- AIML,12,4,8,0,33%,Critical,20 more,2026-10-06,2
37,4MW24AI041,SANIKA,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25%,Critical,24 more,2026-10-06,2
38,4MW24AI042,SHAMANTH K,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-09,1
39,4MW24AI043,SHETTY RASHIK RATHNAKAR,Data Science & GenAI - 3nd Yr- AIML,12,5,7,0,42%,Critical,16 more,2026-10-06,2
40,4MW24AI044,SHODAN B POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-10,0
41,4MW24AI045,SHRAVYA,Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17%,Critical,28 more,2026-09-08,9
42,4MW24AI046,SHREESH A DEVADIGA,Data Science & GenAI - 3nd Yr- AIML,12,12,0,0,100%,Safe,✓ Met,2026-10-10,0
43,4MW24AI047,SHRIYA DEVADIGA,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
44,4MW24AI048,SINCHANA (SUNDARA MADIVALA),Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17%,Critical,28 more,2026-10-06,2
45,4MW24AI049,SINCHANA (MURALI KUPPAYYA MOGAVEERA),Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
46,4MW24AI050,SPOORTHI,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
47,4MW24AI052,SUPRAJA S M,Data Science & GenAI - 3nd Yr- AIML,12,6,6,0,50%,Critical,12 more,2026-10-09,1
48,4MW24AI053,SUPRITHA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
49,4MW24AI054,TEJAS,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-06,2
50,4MW24AI055,TRIPTHI H PADMASHALI,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-09,1
51,4MW24AI056,VAMSH,Data Science & GenAI - 3nd Yr- AIML,12,4,8,0,33%,Critical,20 more,2026-10-06,2
52,4MW24AI057,VANDANA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
53,4MW24AI058,VIGNESH ADIGA,Data Science & GenAI - 3nd Yr- AIML,12,7,5,0,58%,Critical,8 more,2026-09-25,4
54,4MW24AI059,VIHAAN S,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67%,Critical,4 more,2026-10-10,0
55,4MW24AI060,YASHASVI K POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
56,4MW24AI061,Raksha,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
57,4MW25AI400,Dhananjay,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-06,2
58,4MW25AI401,Omkar Rane,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8%,Critical,32 more,2026-09-08,9

#### Section 1: Data Inspection

In [ ]:
"""Q1. Display the first 10 rows, the shape of the DataFrame, and the data types of each column."""
#-----------------------------Write Solution Code-----------------------------
import pandas as pd

print(df.head(10))
print(df.shape)
print(df.dtypes)

      Roll No             Student Name                               Subject  \
0  4MW24AI001                 ABHIJITH  Data Science & GenAI - 3nd Yr- AIML
1  4MW24AI002       ABHISHEK KRISHNA P  Data Science & GenAI - 3nd Yr- AIML
2  4MW24AI003                   ADITYA  Data Science & GenAI - 3nd Yr- AIML
3  4MW24AI004        AKSHATA JAKAREDDY  Data Science & GenAI - 3nd Yr- AIML
4  4MW24AI005                   ANANYA  Data Science & GenAI - 3nd Yr- AIML
5  4MW24AI006              ANANYASHREE  Data Science & GenAI - 3nd Yr- AIML
6  4MW24AI007    ANKITA TARANATH MESTA  Data Science & GenAI - 3nd Yr- AIML
7  4MW24AI008        ANVITH S SHERIGAR  Data Science & GenAI - 3nd Yr- AIML
8  4MW24AI009                  APEKSHA  Data Science & GenAI - 3nd Yr- AIML
9  4MW24AI010  ARLENE VELORA FERNANDES  Data Science & GenAI - 3nd Yr- AIML

   Total Classes  Present  Absent  Excused Attendance %    Status  \
0             12        8       4        0          67%  Critical
1             12        8       4        0          67%  Critical
2             12        1      11        0           8%  Critical
3             12       11       1        0          92%      Safe
4             12       10       2        0          83%   Warning
5             12       10       2        0          83%   Warning
6             12       10       2        0          83%   Warning
7             12       12       0        0         100%      Safe
8             12       10       2        0          83%   Warning
9             12        9       3        0          75%   Warning

  Classes Needed (75%) Last Present Date  Consecutive Absences
0               4 more        2026-10-09                     1
1               4 more        2026-10-09                     1
2              32 more        2026-09-22                     5
3                ✓ Met        2026-10-10                     0
4                ✓ Met        2026-10-09                     1
5                ✓ Met        2026-10-09                     1
6                ✓ Met        2026-10-09                     1
7                ✓ Met        2026-10-10                     0
8                ✓ Met        2026-10-09                     1
9                ✓ Met        2026-10-09                     1
(59, 12)
Roll No                 object
Student Name            object
Subject                 object
Total Classes            int64
Present                  int64
Absent                   int64
Excused                  int64
Attendance %            object
Status                  object
Classes Needed (75%)    object
Last Present Date       object
Consecutive Absences     int64
dtype: object

In [ ]:
"""Q2. Check for missing values in each column. Identify which columns have null values (especially Last Present Date with "Never") and report the count. """
#-----------------------------Write Solution Code-----------------------------
print(df.isnull().sum())
print((df == "Never").sum())
print(df['Last Present Date'].value_counts(dropna=False))

Roll No                 0
Student Name            0
Subject                 0
Total Classes           0
Present                 0
Absent                  0
Excused                 0
Attendance %            0
Status                  0
Classes Needed (75%)    0
Last Present Date       0
Consecutive Absences    0
dtype: int64
Roll No                 0
Student Name            0
Subject                 0
Total Classes           0
Present                 0
Absent                  0
Excused                 0
Attendance %            0
Status                  0
Classes Needed (75%)    0
Last Present Date       2
Consecutive Absences    0
dtype: int64
Last Present Date
2026-10-09    22
2026-10-06    16
2026-10-10    13
2026-09-22     2
Never          2
2026-09-08     2
2026-09-29     1
2026-09-25     1
Name: count, dtype: int64

In [ ]:
"""Q3. Rename the columns to snake_case (e.g., Roll No → roll_no, Student Name → student_name, Attendance % → attendance_pct). Display the updated column list."""
#-----------------------------Write Solution Code-----------------------------
df.columns = df.columns.str.strip().str.lower().str.replace('%','pct').str.replace(r'[^\w]+','_', regex=True).str.strip('_')
print(df.columns.tolist())

['roll_no', 'student_name', 'subject', 'total_classes', 'present', 'absent', 'excused', 'attendance_pct', 'status', 'classes_needed_75pct', 'last_present_date', 'consecutive_absences']

In [ ]:
"""Q4. Convert Attendance % from string format (e.g., "64%") to a numeric float column (0.64 or 64.0). Also convert Last Present Date to datetime, handling "Never" as NaT."""
#-----------------------------Write Solution Code-----------------------------
df['attendance_pct'] = df['attendance_pct'].astype(str).str.replace('%','', regex=False).str.strip()
df['attendance_pct'] = pd.to_numeric(df['attendance_pct'], errors='coerce')

df['last_present_date'] = df['last_present_date'].replace('Never', pd.NaT)
df['last_present_date'] = pd.to_datetime(df['last_present_date'], errors='coerce')

print(df[['attendance_pct', 'last_present_date']].head(10))

   attendance_pct last_present_date
0            67.0        2026-10-09
1            67.0        2026-10-09
2             8.0        2026-09-22
3            92.0        2026-10-10
4            83.0        2026-10-09
5            83.0        2026-10-09
6            83.0        2026-10-09
7           100.0        2026-10-10
8            83.0        2026-10-09
9            75.0        2026-10-09

#### Section 2: Filtering & Selection

In [ ]:
"""Q5. Filter and display all students whose Status is "Critical". Sort them by Attendance % in ascending order."""
#-----------------------------Write Solution Code-----------------------------
critical_df = df[df['status'] == 'Critical'].sort_values('attendance_pct')
print(critical_df)

       roll_no                 student_name  \
32  4MW24AI035                   RAJATH K K
33  4MW24AI036           RAJU ASHOKA RATHOD
2   4MW24AI003                       ADITYA
35  4MW24AI038                       RASHMI
58  4MW25AI401                   Omkar Rane
22  4MW24AI025                     MANMITHA
41  4MW24AI045                      SHRAVYA
44  4MW24AI048  SINCHANA (SUNDARA MADIVALA)
30  4MW24AI033                 PRAMOD ACHAR
37  4MW24AI041                       SANIKA
31  4MW24AI034                   RAJATH H S
25  4MW24AI028               MOURYA RAJ H N
18  4MW24AI021                     KISHAN J
27  4MW24AI030                        NAVYA
51  4MW24AI056                        VAMSH
36  4MW24AI039                       RITHIN
39  4MW24AI043      SHETTY RASHIK RATHNAKAR
47  4MW24AI052                  SUPRAJA S M
12  4MW24AI014            DHANRAJ L POOJARY
53  4MW24AI058                VIGNESH ADIGA
0   4MW24AI001                     ABHIJITH
1   4MW24AI002           ABHISHEK KRISHNA P
54  4MW24AI059                     VIHAAN S

                                 subject  total_classes  present  absent  \
32  Data Science & GenAI - 3nd Yr- AIML              12        0      12
33  Data Science & GenAI - 3nd Yr- AIML              12        0      12
2   Data Science & GenAI - 3nd Yr- AIML              12        1      11
35  Data Science & GenAI - 3nd Yr- AIML              12        1      11
58  Data Science & GenAI - 3nd Yr- AIML              12        1      11
22  Data Science & GenAI - 3nd Yr- AIML              12        2      10
41  Data Science & GenAI - 3nd Yr- AIML              12        2      10
44  Data Science & GenAI - 3nd Yr- AIML              12        2      10
30  Data Science & GenAI - 3nd Yr- AIML              12        3       9
37  Data Science & GenAI - 3nd Yr- AIML              12        3       9
31  Data Science & GenAI - 3nd Yr- AIML              12        3       9
25  Data Science & GenAI - 3nd Yr- AIML              12        3       9
18  Data Science & GenAI - 3nd Yr- AIML              12        3       9
27  Data Science & GenAI - 3nd Yr- AIML              12        3       9
51  Data Science & GenAI - 3nd Yr- AIML              12        4       8
36  Data Science & GenAI - 3nd Yr- AIML              12        4       8
39  Data Science & GenAI - 3nd Yr- AIML              12        5       7
47  Data Science & GenAI - 3nd Yr- AIML              12        6       6
12  Data Science & GenAI - 3nd Yr- AIML              12        6       6
53  Data Science & GenAI - 3nd Yr- AIML              12        7       5
0   Data Science & GenAI - 3nd Yr- AIML              12        8       4
1   Data Science & GenAI - 3nd Yr- AIML              12        8       4
54  Data Science & GenAI - 3nd Yr- AIML              12        8       4

    excused  attendance_pct    status classes_needed_75pct last_present_date  \
32        0             0.0  Critical              36 more               NaT
33        0             0.0  Critical              36 more               NaT
2         0             8.0  Critical              32 more        2026-09-22
35        0             8.0  Critical              32 more        2026-10-06
58        0             8.0  Critical              32 more        2026-09-08
22        0            17.0  Critical              28 more        2026-10-06
41        0            17.0  Critical              28 more        2026-09-08
44        0            17.0  Critical              28 more        2026-10-06
30        0            25.0  Critical              24 more        2026-10-06
37        0            25.0  Critical              24 more        2026-10-06
31        0            25.0  Critical              24 more        2026-10-06
25        0            25.0  Critical              24 more        2026-09-22
18        0            25.0  Critical              24 more        2026-09-29
27        0            25.0  Critical              24 more        2026-10-06
51        0            33.0  Critical              20 more        2026-10-06
36        0            33.0  Critical              20 more        2026-10-06
39        0            42.0  Critical              16 more        2026-10-06
47        0            50.0  Critical              12 more        2026-10-09
12        0            50.0  Critical              12 more        2026-10-06
53        0            58.0  Critical               8 more        2026-09-25
0         0            67.0  Critical               4 more        2026-10-09
1         0            67.0  Critical               4 more        2026-10-09
54        0            67.0  Critical               4 more        2026-10-10

    consecutive_absences
32                    12
33                    12
2                      5
35                     2
58                     9
22                     2
41                     9
44                     2
30                     2
37                     2
31                     2
25                     5
18                     3
27                     2
51                     2
36                     2
39                     2
47                     1
12                     2
53                     4
0                      1
1                      1
54                     0

In [ ]:
"""Q6. Extract all students who have 0 present days (fully absent). List their roll numbers, names, and consecutive absences."""
#-----------------------------Write Solution Code-----------------------------
absent_df = df[df['present'] == 0][['roll_no','student_name','consecutive_absences']]
print(absent_df)

       roll_no        student_name  consecutive_absences
32  4MW24AI035          RAJATH K K                    12
33  4MW24AI036  RAJU ASHOKA RATHOD                    12

In [ ]:
"""Q7. Using .loc and .iloc, display:
(a) All "Safe" students using .loc
(b) The first 15 rows and columns 2-6 using .iloc """
#-----------------------------Write Solution Code-----------------------------
print(df.loc[df['status'] == 'Safe'])
print(df.iloc[0:15, 2:6])

       roll_no                          student_name  \
3   4MW24AI004                     AKSHATA JAKAREDDY
7   4MW24AI008                     ANVITH S SHERIGAR
14  4MW24AI016                            G BHUPATHE
15  4MW24AI018                     HARSHAL G POOJARY
16  4MW24AI019                           JNANESH . S
17  4MW24AI020             KEERTHAN KRISHNA SHERIGAR
21  4MW24AI024                        MANEESH SHETTY
26  4MW24AI029                       MUHAMMED NASHIT
29  4MW24AI032                             PRAGNYA R
38  4MW24AI042                            SHAMANTH K
42  4MW24AI046                    SHREESH A DEVADIGA
43  4MW24AI047                       SHRIYA DEVADIGA
45  4MW24AI049  SINCHANA (MURALI KUPPAYYA MOGAVEERA)

                                 subject  total_classes  present  absent  \
3   Data Science & GenAI - 3nd Yr- AIML              12       11       1
7   Data Science & GenAI - 3nd Yr- AIML              12       12       0
14  Data Science & GenAI - 3nd Yr- AIML              12       11       1
15  Data Science & GenAI - 3nd Yr- AIML              12       11       1
16  Data Science & GenAI - 3nd Yr- AIML              12       11       1
17  Data Science & GenAI - 3nd Yr- AIML              12       11       1
21  Data Science & GenAI - 3nd Yr- AIML              12       11       1
26  Data Science & GenAI - 3nd Yr- AIML              12       11       1
29  Data Science & GenAI - 3nd Yr- AIML              12       11       1
38  Data Science & GenAI - 3nd Yr- AIML              12       11       1
42  Data Science & GenAI - 3nd Yr- AIML              12       12       0
43  Data Science & GenAI - 3nd Yr- AIML              12       11       1
45  Data Science & GenAI - 3nd Yr- AIML              12       11       1

    excused  attendance_pct status classes_needed_75pct last_present_date  \
3         0            92.0   Safe                ✓ Met        2026-10-10
7         0           100.0   Safe                ✓ Met        2026-10-10
14        0            92.0   Safe                ✓ Met        2026-10-10
15        0            92.0   Safe                ✓ Met        2026-10-09
16        0            92.0   Safe                ✓ Met        2026-10-09
17        0            92.0   Safe                ✓ Met        2026-10-09
21        0            92.0   Safe                ✓ Met        2026-10-10
26        0            92.0   Safe                ✓ Met        2026-10-10
29        0            92.0   Safe                ✓ Met        2026-10-10
38        0            92.0   Safe                ✓ Met        2026-10-09
42        0           100.0   Safe                ✓ Met        2026-10-10
43        0            92.0   Safe                ✓ Met        2026-10-10
45        0            92.0   Safe                ✓ Met        2026-10-10

    consecutive_absences
3                      0
7                      0
14                     0
15                     1
16                     1
17                     1
21                     0
26                     0
29                     0
38                     1
42                     0
43                     0
45                     0
                                 subject  total_classes  present  absent
0   Data Science & GenAI - 3nd Yr- AIML              12        8       4
1   Data Science & GenAI - 3nd Yr- AIML              12        8       4
2   Data Science & GenAI - 3nd Yr- AIML              12        1      11
3   Data Science & GenAI - 3nd Yr- AIML              12       11       1
4   Data Science & GenAI - 3nd Yr- AIML              12       10       2
5   Data Science & GenAI - 3nd Yr- AIML              12       10       2
6   Data Science & GenAI - 3nd Yr- AIML              12       10       2
7   Data Science & GenAI - 3nd Yr- AIML              12       12       0
8   Data Science & GenAI - 3nd Yr- AIML              12       10       2
9   Data Science & GenAI - 3nd Yr- AIML              12        9       3
10  Data Science & GenAI - 3nd Yr- AIML              12        9       3
11  Data Science & GenAI - 3nd Yr- AIML              12        9       3
12  Data Science & GenAI - 3nd Yr- AIML              12        6       6
13  Data Science & GenAI - 3nd Yr- AIML              12        9       3
14  Data Science & GenAI - 3nd Yr- AIML              12       11       1

In [ ]:
"""Q8. Find all students whose Consecutive Absences is greater than or equal to 5. Display their name, status, and last present date."""
#-----------------------------Write Solution Code-----------------------------
print(df[df['consecutive_absences'] >= 5][['student_name','status','last_present_date']])

          student_name    status last_present_date
2               ADITYA  Critical        2026-09-22
25      MOURYA RAJ H N  Critical        2026-09-22
32          RAJATH K K  Critical               NaT
33  RAJU ASHOKA RATHOD  Critical               NaT
41             SHRAVYA  Critical        2026-09-08
58          Omkar Rane  Critical        2026-09-08

### Section 3: Grouping & Aggregation

In [ ]:
"""Q9. Group the data by Status and compute: 
a) Count of students 
b) Average attendance %  
c) Maximum consecutive absences"""
#-----------------------------Write Solution Code-----------------------------
print(df.groupby('status').agg(
    student_count=('roll_no','count'),
    avg_attendance=('attendance_pct','mean'),
    max_consecutive_absences=('consecutive_absences','max')
))

          student_count  avg_attendance  max_consecutive_absences
status
Critical             23       30.086957                        12
Safe                 13       93.230769                         1
Warning              23       80.565217                         2

In [20]:
"""Q10. Create a new column Attendance Category:
≥ 90% → "Excellent"
75-89% → "Good"
60-74% → "Average"
< 60% → "Poor"
Then use groupby() to count students in each category."""
#-----------------------------Write Solution Code-----------------------------
def get_category(x):
    if x >= 90:
        return "Excellent"
    elif x >= 75:
        return "Good"
    elif x >= 60:
        return "Average"
    else:
        return "Poor"

df['attendance_category'] = df['attendance_pct'].apply(get_category)
print(df.groupby('attendance_category').size())

attendance_category
Average       3
Excellent    13
Good         23
Poor         20
dtype: int64

In [21]:
"""Q11. Calculate the total number of classes conducted (sum of Total Classes) and the total present/absent counts across all students using .agg()."""
#-----------------------------Write Solution Code-----------------------------
print(df.agg(
    total_classes=('total_classes','sum'),
    total_present=('present','sum'),
    total_absent=('absent','sum')
))

               total_classes  present  absent
total_classes          708.0      NaN     NaN
total_present            NaN    451.0     NaN
total_absent             NaN      NaN   257.0

In [22]:
"""Q12. Group by Status and use .agg() to find:
a)min, max, and mean of Present
b)sum of Absent"""
#-----------------------------Write Solution Code-----------------------------
print(df.groupby('status').agg(
    min_present=('present','min'),
    max_present=('present','max'),
    mean_present=('present','mean'),
    sum_absent=('absent','sum')
))

          min_present  max_present  mean_present  sum_absent
status
Critical            0            8      3.608696         193
Safe               11           12     11.153846          11
Warning             9           10      9.695652          53

### Section 4: Feature Engineering & Transformation

In [23]:
"""Q13. Create a new column Risk Score using the formula:
Risk Score = (Absent * 0.4) + (Consecutive Absences * 0.6)
Display the top 10 students with the highest risk score."""
#-----------------------------Write Solution Code-----------------------------
df['risk_score'] = (df['absent'] * 0.4) + (df['consecutive_absences'] * 0.6)
print(df.sort_values('risk_score', ascending=False).head(10))

       roll_no                 student_name  \
33  4MW24AI036           RAJU ASHOKA RATHOD
32  4MW24AI035                   RAJATH K K
58  4MW25AI401                   Omkar Rane
41  4MW24AI045                      SHRAVYA
2   4MW24AI003                       ADITYA
25  4MW24AI028               MOURYA RAJ H N
35  4MW24AI038                       RASHMI
18  4MW24AI021                     KISHAN J
22  4MW24AI025                     MANMITHA
44  4MW24AI048  SINCHANA (SUNDARA MADIVALA)

                                 subject  total_classes  present  absent  \
33  Data Science & GenAI - 3nd Yr- AIML              12        0      12
32  Data Science & GenAI - 3nd Yr- AIML              12        0      12
58  Data Science & GenAI - 3nd Yr- AIML              12        1      11
41  Data Science & GenAI - 3nd Yr- AIML              12        2      10
2   Data Science & GenAI - 3nd Yr- AIML              12        1      11
25  Data Science & GenAI - 3nd Yr- AIML              12        3       9
35  Data Science & GenAI - 3nd Yr- AIML              12        1      11
18  Data Science & GenAI - 3nd Yr- AIML              12        3       9
22  Data Science & GenAI - 3nd Yr- AIML              12        2      10
44  Data Science & GenAI - 3nd Yr- AIML              12        2      10

    excused  attendance_pct    status classes_needed_75pct last_present_date  \
33        0             0.0  Critical              36 more               NaT
32        0             0.0  Critical              36 more               NaT
58        0             8.0  Critical              32 more        2026-09-08
41        0            17.0  Critical              28 more        2026-09-08
2         0             8.0  Critical              32 more        2026-09-22
25        0            25.0  Critical              24 more        2026-09-22
35        0             8.0  Critical              32 more        2026-10-06
18        0            25.0  Critical              24 more        2026-09-29
22        0            17.0  Critical              28 more        2026-10-06
44        0            17.0  Critical              28 more        2026-10-06

    consecutive_absences attendance_category  risk_score
33                    12                Poor        12.0
32                    12                Poor        12.0
58                     9                Poor         9.8
41                     9                Poor         9.4
2                      5                Poor         7.4
25                     5                Poor         6.6
35                     2                Poor         5.6
18                     3                Poor         5.4
22                     2                Poor         5.2
44                     2                Poor         5.2

In [25]:
"""Q14. Add a column Classes Needed (Numeric) by extracting the numeric value from the Classes Needed (75%) column (e.g., "5 more" → 5, "✓ Met" → 0)."""
#-----------------------------Write Solution Code-----------------------------
print(df.columns.tolist())

target_col = [c for c in df.columns if 'classes' in c and 'needed' in c][0]
print(target_col)

df['classes_needed_numeric'] = df[target_col].astype(str).str.extract(r'(\d+)').fillna(0).astype(int)

print(df[['{}'.format(target_col), 'classes_needed_numeric']].head(10))

['roll_no', 'student_name', 'subject', 'total_classes', 'present', 'absent', 'excused', 'attendance_pct', 'status', 'classes_needed_75pct', 'last_present_date', 'consecutive_absences', 'attendance_category', 'risk_score']
classes_needed_75pct
  classes_needed_75pct  classes_needed_numeric
0               4 more                       4
1               4 more                       4
2              32 more                      32
3                ✓ Met                       0
4                ✓ Met                       0
5                ✓ Met                       0
6                ✓ Met                       0
7                ✓ Met                       0
8                ✓ Met                       0
9                ✓ Met                       0

In [26]:
"""Q15. Using apply() with a lambda function, create a column Attendance Flag that returns:
a)"Defaulter" if attendance < 75%
b)"Safe" otherwise """
#-----------------------------Write Solution Code-----------------------------
df['attendance_flag'] = df['attendance_pct'].apply(lambda x: "Defaulter" if x < 75 else "Safe")
print(df['attendance_flag'])

0     Defaulter
1     Defaulter
2     Defaulter
3          Safe
4          Safe
5          Safe
6          Safe
7          Safe
8          Safe
9          Safe
10         Safe
11         Safe
12    Defaulter
13         Safe
14         Safe
15         Safe
16         Safe
17         Safe
18    Defaulter
19         Safe
20         Safe
21         Safe
22    Defaulter
23         Safe
24         Safe
25    Defaulter
26         Safe
27    Defaulter
28         Safe
29         Safe
30    Defaulter
31    Defaulter
32    Defaulter
33    Defaulter
34         Safe
35    Defaulter
36    Defaulter
37    Defaulter
38         Safe
39    Defaulter
40         Safe
41    Defaulter
42         Safe
43         Safe
44    Defaulter
45         Safe
46         Safe
47    Defaulter
48         Safe
49         Safe
50         Safe
51    Defaulter
52         Safe
53    Defaulter
54    Defaulter
55         Safe
56         Safe
57         Safe
58    Defaulter
Name: attendance_flag, dtype: object

In [27]:
"""Q16. Use pd.cut() to bin students into attendance ranges: [0-50, 50-75, 75-90, 90-100] and label them as ["Critical", "Warning", "Good", "Excellent"]."""
#-----------------------------Write Solution Code-----------------------------
df['attendance_bin'] = pd.cut(df['attendance_pct'], bins=[0,50,75,90,100], labels=["Critical","Warning","Good","Excellent"])
print(df['attendance_bin'])

0       Warning
1       Warning
2      Critical
3     Excellent
4          Good
5          Good
6          Good
7     Excellent
8          Good
9       Warning
10      Warning
11      Warning
12     Critical
13      Warning
14    Excellent
15    Excellent
16    Excellent
17    Excellent
18     Critical
19         Good
20         Good
21    Excellent
22     Critical
23         Good
24      Warning
25     Critical
26    Excellent
27     Critical
28         Good
29    Excellent
30     Critical
31     Critical
32          NaN
33          NaN
34         Good
35     Critical
36     Critical
37     Critical
38    Excellent
39     Critical
40      Warning
41     Critical
42    Excellent
43    Excellent
44     Critical
45    Excellent
46         Good
47     Critical
48         Good
49         Good
50      Warning
51     Critical
52         Good
53      Warning
54      Warning
55         Good
56         Good
57         Good
58     Critical
Name: attendance_bin, dtype: category
Categories (4, object): ['Critical' < 'Warning' < 'Good' < 'Excellent']

### Section 5: Advanced Analysis

In [28]:
"""Q17. Using pivot_table(), create a summary showing the count of students by Status and Attendance Category (created in Q10)."""
#-----------------------------Write Solution Code-----------------------------
print(pd.pivot_table(df, index='status', columns='attendance_category', values='roll_no', aggfunc='count', fill_value=0))

attendance_category  Average  Excellent  Good  Poor
status
Critical                   3          0     0    20
Safe                       0         13     0     0
Warning                    0          0    23     0

In [29]:
"""Q18. Identify duplicate student names (e.g., "ANANYA", "DISHA") and display all rows where the base name repeats. Use string manipulation to extract the base name."""
#-----------------------------Write Solution Code-----------------------------
df['base_name'] = df['student_name'].astype(str).str.split().str[0]
dup_names = df['base_name'][df['base_name'].duplicated(keep=False)]
print(df[df['base_name'].isin(dup_names)].sort_values('base_name'))

       roll_no                          student_name  \
31  4MW24AI034                            RAJATH H S
32  4MW24AI035                            RAJATH K K
44  4MW24AI048           SINCHANA (SUNDARA MADIVALA)
45  4MW24AI049  SINCHANA (MURALI KUPPAYYA MOGAVEERA)

                                 subject  total_classes  present  absent  \
31  Data Science & GenAI - 3nd Yr- AIML              12        3       9
32  Data Science & GenAI - 3nd Yr- AIML              12        0      12
44  Data Science & GenAI - 3nd Yr- AIML              12        2      10
45  Data Science & GenAI - 3nd Yr- AIML              12       11       1

    excused  attendance_pct    status classes_needed_75pct last_present_date  \
31        0            25.0  Critical              24 more        2026-10-06
32        0             0.0  Critical              36 more               NaT
44        0            17.0  Critical              28 more        2026-10-06
45        0            92.0      Safe                ✓ Met        2026-10-10

    consecutive_absences attendance_category  risk_score  \
31                     2                Poor         4.8
32                    12                Poor        12.0
44                     2                Poor         5.2
45                     0           Excellent         0.4

    classes_needed_numeric attendance_flag attendance_bin base_name
31                      24       Defaulter       Critical    RAJATH
32                      36       Defaulter            NaN    RAJATH
44                      28       Defaulter       Critical  SINCHANA
45                       0            Safe      Excellent  SINCHANA

In [30]:
""""Q19. Merge this dataset with a hypothetical Student_Details DataFrame containing Roll No, Branch, and Semester. Perform an inner join and display the merged result."""
#-----------------------------Write Solution Code-----------------------------
student_details = pd.DataFrame({
    'roll_no': df['roll_no'].unique(),
    'branch': 'AIML',
    'semester': 4
})
merged_df = pd.merge(df, student_details, on='roll_no', how='inner')
print(merged_df.head())

      roll_no        student_name                               subject  \
0  4MW24AI001            ABHIJITH  Data Science & GenAI - 3nd Yr- AIML
1  4MW24AI002  ABHISHEK KRISHNA P  Data Science & GenAI - 3nd Yr- AIML
2  4MW24AI003              ADITYA  Data Science & GenAI - 3nd Yr- AIML
3  4MW24AI004   AKSHATA JAKAREDDY  Data Science & GenAI - 3nd Yr- AIML
4  4MW24AI005              ANANYA  Data Science & GenAI - 3nd Yr- AIML

   total_classes  present  absent  excused  attendance_pct    status  \
0             12        8       4        0            67.0  Critical
1             12        8       4        0            67.0  Critical
2             12        1      11        0             8.0  Critical
3             12       11       1        0            92.0      Safe
4             12       10       2        0            83.0   Warning

  classes_needed_75pct last_present_date  consecutive_absences  \
0               4 more        2026-10-09                     1
1               4 more        2026-10-09                     1
2              32 more        2026-09-22                     5
3                ✓ Met        2026-10-10                     0
4                ✓ Met        2026-10-09                     1

  attendance_category  risk_score  classes_needed_numeric attendance_flag  \
0             Average         2.2                       4       Defaulter
1             Average         2.2                       4       Defaulter
2                Poor         7.4                      32       Defaulter
3           Excellent         0.4                       0            Safe
4                Good         1.4                       0            Safe

  attendance_bin base_name branch  semester
0        Warning  ABHIJITH   AIML         4
1        Warning  ABHISHEK   AIML         4
2       Critical    ADITYA   AIML         4
3      Excellent   AKSHATA   AIML         4
4           Good    ANANYA   AIML         4

In [32]:
"""Q20. Export the following to separate CSV files:
(a) All "Critical" students
(b) Summary statistics grouped by Status
(c) Top 10 students by Risk Score"""
#-----------------------------Write Solution Code-----------------------------

print(df.columns.tolist())

status_col = [c for c in df.columns if 'status' in c][0]
roll_col = [c for c in df.columns if 'roll' in c][0]

critical_students = df[df[status_col] == 'Critical']
critical_students.to_csv('critical_students.csv', index=False)

summary = df.groupby(status_col).agg(
    avg_attendance=('attendance_pct','mean'),
    total_students=(roll_col,'count')
)
summary.to_csv('summary_by_status.csv')

top10_risk = df.sort_values('risk_score', ascending=False).head(10)
top10_risk.to_csv('top10_risk_score.csv', index=False)

print("Files exported successfully")
print(critical_students.shape)
print(summary)
print(top10_risk.shape)

['roll_no', 'student_name', 'subject', 'total_classes', 'present', 'absent', 'excused', 'attendance_pct', 'status', 'classes_needed_75pct', 'last_present_date', 'consecutive_absences', 'attendance_category', 'risk_score', 'classes_needed_numeric', 'attendance_flag', 'attendance_bin', 'base_name']
Files exported successfully
(23, 18)
          avg_attendance  total_students
status
Critical       30.086957              23
Safe           93.230769              13
Warning        80.565217              23
(10, 18)

In [ ]:
"""Q11. Calculate the total number of classes conducted (sum of Total Classes) and the total present/absent counts across all students using .agg()."""
#-----------------------------Write Solution Code-----------------------------

In [ ]:
"""Q12. Group by Status and use .agg() to find:
a)min, max, and mean of Present
b)sum of Absent"""
#-----------------------------Write Solution Code-----------------------------

### Section 4: Feature Engineering & Transformation

In [35]:
"""Q13. Create a new column Risk Score using the formula:
Risk Score = (Absent * 0.4) + (Consecutive Absences * 0.6)
Display the top 10 students with the highest risk score."""
#-----------------------------Write Solution Code-----------------------------
df['risk_score'] = (df['absent'] * 0.4) + (df['consecutive_absences'] * 0.6)

top_10_risk = df.sort_values('risk_score', ascending=False).head(10)

print(top_10_risk.head(10))

       roll_no                 student_name  \
33  4MW24AI036           RAJU ASHOKA RATHOD
32  4MW24AI035                   RAJATH K K
58  4MW25AI401                   Omkar Rane
41  4MW24AI045                      SHRAVYA
2   4MW24AI003                       ADITYA
25  4MW24AI028               MOURYA RAJ H N
35  4MW24AI038                       RASHMI
18  4MW24AI021                     KISHAN J
22  4MW24AI025                     MANMITHA
44  4MW24AI048  SINCHANA (SUNDARA MADIVALA)

                                 subject  total_classes  present  absent  \
33  Data Science & GenAI - 3nd Yr- AIML              12        0      12
32  Data Science & GenAI - 3nd Yr- AIML              12        0      12
58  Data Science & GenAI - 3nd Yr- AIML              12        1      11
41  Data Science & GenAI - 3nd Yr- AIML              12        2      10
2   Data Science & GenAI - 3nd Yr- AIML              12        1      11
25  Data Science & GenAI - 3nd Yr- AIML              12        3       9
35  Data Science & GenAI - 3nd Yr- AIML              12        1      11
18  Data Science & GenAI - 3nd Yr- AIML              12        3       9
22  Data Science & GenAI - 3nd Yr- AIML              12        2      10
44  Data Science & GenAI - 3nd Yr- AIML              12        2      10

    excused  attendance_pct    status classes_needed_75pct last_present_date  \
33        0             0.0  Critical              36 more               NaT
32        0             0.0  Critical              36 more               NaT
58        0             8.0  Critical              32 more        2026-09-08
41        0            17.0  Critical              28 more        2026-09-08
2         0             8.0  Critical              32 more        2026-09-22
25        0            25.0  Critical              24 more        2026-09-22
35        0             8.0  Critical              32 more        2026-10-06
18        0            25.0  Critical              24 more        2026-09-29
22        0            17.0  Critical              28 more        2026-10-06
44        0            17.0  Critical              28 more        2026-10-06

    consecutive_absences attendance_category  risk_score  \
33                    12                Poor        12.0
32                    12                Poor        12.0
58                     9                Poor         9.8
41                     9                Poor         9.4
2                      5                Poor         7.4
25                     5                Poor         6.6
35                     2                Poor         5.6
18                     3                Poor         5.4
22                     2                Poor         5.2
44                     2                Poor         5.2

    classes_needed_numeric attendance_flag attendance_bin base_name
33                      36       Defaulter            NaN      RAJU
32                      36       Defaulter            NaN    RAJATH
58                      32       Defaulter       Critical     Omkar
41                      28       Defaulter       Critical   SHRAVYA
2                       32       Defaulter       Critical    ADITYA
25                      24       Defaulter       Critical    MOURYA
35                      32       Defaulter       Critical    RASHMI
18                      24       Defaulter       Critical    KISHAN
22                      28       Defaulter       Critical  MANMITHA
44                      28       Defaulter       Critical  SINCHANA

In [37]:
"""Q14. Add a column Classes Needed (Numeric) by extracting the numeric value from the Classes Needed (75%) column (e.g., "5 more" → 5, "✓ Met" → 0)."""
#-----------------------------Write Solution Code-----------------------------
col = [c for c in df.columns if 'needed' in c][0]
print(f"Found column: {col}")

df['classes_needed_numeric'] = df[col].astype(str).str.extract(r'(\d+)').fillna(0).astype(int)

print(df[[col, 'classes_needed_numeric']].head(10))

Found column: classes_needed_75pct
  classes_needed_75pct  classes_needed_numeric
0               4 more                       4
1               4 more                       4
2              32 more                      32
3                ✓ Met                       0
4                ✓ Met                       0
5                ✓ Met                       0
6                ✓ Met                       0
7                ✓ Met                       0
8                ✓ Met                       0
9                ✓ Met                       0

In [38]:
"""Q15. Using apply() with a lambda function, create a column Attendance Flag that returns:
a)"Defaulter" if attendance < 75%
b)"Safe" otherwise """
#-----------------------------Write Solution Code-----------------------------
df['attendance_flag'] = df['attendance_pct'].apply(lambda x: 'Defaulter' if x < 75 else 'Safe')

print(df[['attendance_pct','attendance_flag']].head(10))

   attendance_pct attendance_flag
0            67.0       Defaulter
1            67.0       Defaulter
2             8.0       Defaulter
3            92.0            Safe
4            83.0            Safe
5            83.0            Safe
6            83.0            Safe
7           100.0            Safe
8            83.0            Safe
9            75.0            Safe

In [39]:
"""Q16. Use pd.cut() to bin students into attendance ranges: [0-50, 50-75, 75-90, 90-100] and label them as ["Critical", "Warning", "Good", "Excellent"]."""
#-----------------------------Write Solution Code-----------------------------
df['attendance_range'] = pd.cut(
    df['attendance_pct'],
    bins=[0, 50, 75, 90, 100],
    labels=["Critical", "Warning", "Good", "Excellent"]
)

print(df[['attendance_pct','attendance_range']].head(10))

   attendance_pct attendance_range
0            67.0          Warning
1            67.0          Warning
2             8.0         Critical
3            92.0        Excellent
4            83.0             Good
5            83.0             Good
6            83.0             Good
7           100.0        Excellent
8            83.0             Good
9            75.0          Warning

### Section 5: Advanced Analysis

In [40]:
"""Q17. Using pivot_table(), create a summary showing the count of students by Status and Attendance Category (created in Q10)."""
#-----------------------------Write Solution Code-----------------------------
result = df.pivot_table(
    index='status',
    columns='attendance_category',
    values='roll_no' if 'roll_no' in df.columns else df.columns[0],
    aggfunc='count',
    fill_value=0
)

print(result)

attendance_category  Average  Excellent  Good  Poor
status
Critical                   3          0     0    20
Safe                       0         13     0     0
Warning                    0          0    23     0

In [42]:
"""Q18. Identify duplicate student names (e.g., "ANANYA", "DISHA") and display all rows where the base name repeats. Use string manipulation to extract the base name."""
#-----------------------------Write Solution Code-----------------------------
name_col = [c for c in df.columns if 'name' in c.lower()][0]
print(f"Using column: {name_col}")

df['base_name'] = df[name_col].astype(str).str.replace(r'\(.*\)', '', regex=True).str.replace(r'-.*', '', regex=True).str.strip().str.upper()

duplicate_bases = df['base_name'].value_counts()
duplicate_bases = duplicate_bases[duplicate_bases > 1].index

duplicate_rows = df[df['base_name'].isin(duplicate_bases)].sort_values('base_name')

print(duplicate_rows)

Using column: student_name
       roll_no                          student_name  \
44  4MW24AI048           SINCHANA (SUNDARA MADIVALA)
45  4MW24AI049  SINCHANA (MURALI KUPPAYYA MOGAVEERA)

                                 subject  total_classes  present  absent  \
44  Data Science & GenAI - 3nd Yr- AIML              12        2      10
45  Data Science & GenAI - 3nd Yr- AIML              12       11       1

    excused  attendance_pct    status classes_needed_75pct last_present_date  \
44        0            17.0  Critical              28 more        2026-10-06
45        0            92.0      Safe                ✓ Met        2026-10-10

    consecutive_absences attendance_category  risk_score  \
44                     2                Poor         5.2
45                     0           Excellent         0.4

    classes_needed_numeric attendance_flag attendance_bin base_name  \
44                      28       Defaulter       Critical  SINCHANA
45                       0            Safe      Excellent  SINCHANA

   attendance_range
44         Critical
45        Excellent

In [43]:
""""Q19. Merge this dataset with a hypothetical Student_Details DataFrame containing Roll No, Branch, and Semester. Perform an inner join and display the merged result."""
#-----------------------------Write Solution Code-----------------------------
merged_df = pd.merge(df, student_details, on='roll_no', how='inner')
print(merged_df.head())

      roll_no        student_name                               subject  \
0  4MW24AI001            ABHIJITH  Data Science & GenAI - 3nd Yr- AIML
1  4MW24AI002  ABHISHEK KRISHNA P  Data Science & GenAI - 3nd Yr- AIML
2  4MW24AI003              ADITYA  Data Science & GenAI - 3nd Yr- AIML
3  4MW24AI004   AKSHATA JAKAREDDY  Data Science & GenAI - 3nd Yr- AIML
4  4MW24AI005              ANANYA  Data Science & GenAI - 3nd Yr- AIML

   total_classes  present  absent  excused  attendance_pct    status  \
0             12        8       4        0            67.0  Critical
1             12        8       4        0            67.0  Critical
2             12        1      11        0             8.0  Critical
3             12       11       1        0            92.0      Safe
4             12       10       2        0            83.0   Warning

  classes_needed_75pct  ... consecutive_absences  attendance_category  \
0               4 more  ...                    1              Average
1               4 more  ...                    1              Average
2              32 more  ...                    5                 Poor
3                ✓ Met  ...                    0            Excellent
4                ✓ Met  ...                    1                 Good

  risk_score  classes_needed_numeric  attendance_flag attendance_bin  \
0        2.2                       4        Defaulter        Warning
1        2.2                       4        Defaulter        Warning
2        7.4                      32        Defaulter       Critical
3        0.4                       0             Safe      Excellent
4        1.4                       0             Safe           Good

            base_name attendance_range branch semester
0            ABHIJITH          Warning   AIML        4
1  ABHISHEK KRISHNA P          Warning   AIML        4
2              ADITYA         Critical   AIML        4
3   AKSHATA JAKAREDDY        Excellent   AIML        4
4              ANANYA             Good   AIML        4

[5 rows x 21 columns]

In [44]:
"""Q20. Export the following to separate CSV files:
(a) All "Critical" students
(b) Summary statistics grouped by Status
(c) Top 10 students by Risk Score"""
#-----------------------------Write Solution Code-----------------------------

critical_students = df[df['attendance_range'] == 'Critical']
critical_students.to_csv('critical_students.csv', index=False)

status_col = [c for c in df.columns if 'status' in c.lower()][0]
status_summary = df.groupby(status_col).describe()
status_summary.to_csv('status_summary.csv')


risk_col = [c for c in df.columns if 'risk' in c.lower()][0]
top_10_risk = df.sort_values(by=risk_col, ascending=False).head(10)
top_10_risk.to_csv('top_10_risk_score.csv', index=False)

print("Exported 3 files successfully")
print(f"(a) Critical students: {len(critical_students)} rows")
print(f"(b) Status summary: \n{status_summary.head()}")
print(f"(c) Top 10 Risk: \n{top_10_risk}")

Exported 3 files successfully
(a) Critical students: 17 rows
(b) Status summary:
         total_classes                                          present  \
                 count  mean   min   25%   50%   75%   max  std   count
status
Critical          23.0  12.0  12.0  12.0  12.0  12.0  12.0  0.0    23.0
Safe              13.0  12.0  12.0  12.0  12.0  12.0  12.0  0.0    13.0
Warning           23.0  12.0  12.0  12.0  12.0  12.0  12.0  0.0    23.0

                     ... risk_score           classes_needed_numeric  \
               mean  ...        max       std                  count
status               ...
Critical   3.608696  ...       12.0  2.843313                   23.0
Safe      11.153846  ...        1.0  0.360911                   13.0
Warning    9.695652  ...        2.4  0.414748                   23.0


               mean  min   25%   50%   75%   max       std
status
Critical  21.565217  4.0  14.0  24.0  28.0  36.0  10.07168
Safe       0.000000  0.0   0.0   0.0   0.0   0.0   0.00000
Warning    0.000000  0.0   0.0   0.0   0.0   0.0   0.00000

[3 rows x 72 columns]
(c) Top 10 Risk:
       roll_no                 student_name  \
33  4MW24AI036           RAJU ASHOKA RATHOD
32  4MW24AI035                   RAJATH K K
58  4MW25AI401                   Omkar Rane
41  4MW24AI045                      SHRAVYA
2   4MW24AI003                       ADITYA
25  4MW24AI028               MOURYA RAJ H N
35  4MW24AI038                       RASHMI
18  4MW24AI021                     KISHAN J
22  4MW24AI025                     MANMITHA
44  4MW24AI048  SINCHANA (SUNDARA MADIVALA)

                                 subject  total_classes  present  absent  \
33  Data Science & GenAI - 3nd Yr- AIML              12        0      12
32  Data Science & GenAI - 3nd Yr- AIML              12        0      12
58  Data Science & GenAI - 3nd Yr- AIML              12        1      11
41  Data Science & GenAI - 3nd Yr- AIML              12        2      10
2   Data Science & GenAI - 3nd Yr- AIML              12        1      11
25  Data Science & GenAI - 3nd Yr- AIML              12        3       9
35  Data Science & GenAI - 3nd Yr- AIML              12        1      11
18  Data Science & GenAI - 3nd Yr- AIML              12        3       9
22  Data Science & GenAI - 3nd Yr- AIML              12        2      10
44  Data Science & GenAI - 3nd Yr- AIML              12        2      10

    excused  attendance_pct    status classes_needed_75pct last_present_date  \
33        0             0.0  Critical              36 more               NaT
32        0             0.0  Critical              36 more               NaT
58        0             8.0  Critical              32 more        2026-09-08
41        0            17.0  Critical              28 more        2026-09-08
2         0             8.0  Critical              32 more        2026-09-22
25        0            25.0  Critical              24 more        2026-09-22
35        0             8.0  Critical              32 more        2026-10-06
18        0            25.0  Critical              24 more        2026-09-29
22        0            17.0  Critical              28 more        2026-10-06
44        0            17.0  Critical              28 more        2026-10-06

    consecutive_absences attendance_category  risk_score  \
33                    12                Poor        12.0
32                    12                Poor        12.0
58                     9                Poor         9.8
41                     9                Poor         9.4
2                      5                Poor         7.4
25                     5                Poor         6.6
35                     2                Poor         5.6
18                     3                Poor         5.4
22                     2                Poor         5.2
44                     2                Poor         5.2

    classes_needed_numeric attendance_flag attendance_bin           base_name  \
33                      36       Defaulter            NaN  RAJU ASHOKA RATHOD
32                      36       Defaulter            NaN          RAJATH K K
58                      32       Defaulter       Critical          OMKAR RANE
41                      28       Defaulter       Critical             SHRAVYA
2                       32       Defaulter       Critical              ADITYA
25                      24       Defaulter       Critical      MOURYA RAJ H N
35                      32       Defaulter       Critical              RASHMI
18                      24       Defaulter       Critical            KISHAN J
22                      28       Defaulter       Critical            MANMITHA
44                      28       Defaulter       Critical            SINCHANA

   attendance_range
33              NaN
32              NaN
58         Critical
41         Critical
2          Critical
25         Critical
35         Critical
18         Critical
22         Critical
44         Critical